Add copyright, fix config location, fix exits, build txz

diff --git a/gocr.SlackBuild b/gocr.SlackBuild
--- a/gocr.SlackBuild
+++ b/gocr.SlackBuild
@@ -1,13 +1,31 @@
 #!/bin/sh
 #
-# SlackBuild for GOCR
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for GOCR
+# Copyright (C) 2006,2007,2009,2010,2012 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
+# Visit SlackPack at http://sotirov-bg.net/slackpack/
+#
+# $Id: gocr.SlackBuild,v 1.6 2012/11/24 16:26:51 gsotirov Exp $
 #
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=gocr
-VERSION=0.48
+VERSION=0.49
 ARCH=${ARCH:-i486}
 BUILD=1
 
@@ -34,18 +52,18 @@ mkdir -p $PKG
 
 # Extract the source
 cd $TMP
-tar -zxvf $CWD/$NAME-$VERSION.tar.gz
+tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 3
 cd $SRC
 fix_source
 
 # Configure
 CFLAGS=$SLKCFLAGS \
 ./configure --prefix=/usr \
-            --sysconfdir=/etc || exit 1
+            --sysconfdir=/etc || exit 4
 
 # Build & install
 make -j4 || exit 2
-make DESTDIR=$PKG/usr install || exit 3
+make DESTDIR=$PKG/usr install || exit 5
 
 # Prepare
 bin_perms $PKG
@@ -65,13 +83,15 @@ install -m 644 $CWD/slack-desc     $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack
 install -m 644 $CWD/slack-required $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Pack
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
-makepkg -l y -c n $PKG_DIR/$PKGNAME.tgz
+makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
 cd $PKG_DIR
-md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
+md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Cleanup (optional)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
